name: Android CI

on:
  push:
    branches: ["wide-search"]
  pull_request:
    branches: ["wide-search"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Initialize Submodules (Only for the first build)
      run: |
        if [ ! -f .submodule_initialized ]; then
          git submodule update --init --recursive
          touch .submodule_initialized
        fi

    - name: Build with Gradle
      run: ./gradlew build
